# Generated by Django 2.1.5 on 2019-02-08 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hora_extra', '0002_horaextra_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='funcionario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='funcionario.Funcionario'),
        ),
    ]
