# Generated by Django 2.1.5 on 2019-02-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_auto_20190208_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.ManyToManyField(default=1, to='departamento.Departamento'),
        ),
    ]
