# Generated by Django 2.1.1 on 2020-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionario", "0009_auto_20190304_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="de_ferias",
            field=models.BooleanField(default=False),
        ),
    ]
