# Generated by Django 2.1.1 on 2020-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funcionario", "0010_funcionario_de_ferias"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="imagem",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
